# Generated by Django 4.2.4 on 2023-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image_url', models.CharField(max_length=2000)),
                ('heading', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'home_descriptions',
            },
        ),
    ]
