# Generated by Django 4.2.4 on 2023-09-04 06:57

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedescription',
            name='created_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homedescription',
            name='banner_image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='homedescription',
            name='heading',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homedescription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
